# Generated by Django 2.0.13 on 2022-05-27 16:18

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '__latest__'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatusUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.CharField(blank=True, max_length=255, null=True)),
                ('datos', models.TextField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], default='D', max_length=1)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_adopcion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('G', 'Gato'), ('P', 'Perro')], default='G', max_length=2)),
                ('estado', models.CharField(choices=[('D', 'En Adopción'), ('R', 'Reservado'), ('A', 'Adoptado')], default='D', max_length=2)),
                ('destacado', models.BooleanField(default=False)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gato',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('N', 'No asignado'), ('P', 'En proceso de contacto con el candidato'), ('R', 'Reservado'), ('A', 'Adoptado'), ('D', 'Descartado'), ('U', 'Duplicado'), ('T', 'Transitado')], default='N', max_length=1)),
                ('hash', models.CharField(max_length=255)),
                ('persona_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('A', 'Pre Adopción - Gatos'), ('AP', 'Pre Adopción - Perros'), ('T', 'Tránsito - Gatos'), ('TP', 'Tránsito - Perros')], default='A', max_length=2)),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.FormEntry')),
                ('gato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
