# Generated by Django 2.0.13 on 2022-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
