# Generated by Django 2.0.13 on 2022-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0004_animal_edad_en_meses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AddField(
            model_name='catususer',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
