# Generated by Django 2.0.13 on 2022-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0006_auto_20220701_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='catususer',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
