# Generated by Django 2.0.13 on 2022-08-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0007_catususer_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gato_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], default='D', max_length=1)),
                ('gato_color', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('gato_edad', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_vacunacion_antirabica', models.BooleanField(default=False)),
                ('gato_vacunacion_antirabica_fecha', models.DateField(blank=True, null=True)),
                ('gato_vacunacion_antirabica_notas', models.TextField(blank=True, null=True)),
                ('gato_vacunacion_triple_1_dosis', models.BooleanField(default=False)),
                ('gato_vacunacion_triple_1_dosis_fecha', models.DateField(blank=True, null=True)),
                ('gato_vacunacion_triple_1_dosis_notas', models.TextField(blank=True, null=True)),
                ('gato_vacunacion_triple_2_dosis', models.BooleanField(default=False)),
                ('gato_vacunacion_triple_2_dosis_fecha', models.DateField(blank=True, null=True)),
                ('gato_vacunacion_triple_2_dosis_notas', models.TextField(blank=True, null=True)),
                ('perro_vacunacion_quintuple_1_dosis', models.BooleanField(default=False)),
                ('perro_vacunacion_quintuple_1_dosis_fecha', models.DateField(blank=True, null=True)),
                ('perro_vacunacion_quintuple_1_dosis_notas', models.TextField(blank=True, null=True)),
                ('perro_vacunacion_quintuple_2_dosis', models.BooleanField(default=False)),
                ('perro_vacunacion_quintuple_2_dosis_fecha', models.DateField(blank=True, null=True)),
                ('perro_vacunacion_quintuple_2_dosis_notas', models.TextField(blank=True, null=True)),
                ('perro_vacunacion_sextuple_1_dosis', models.BooleanField(default=False)),
                ('perro_vacunacion_sextuple_1_dosis_fecha', models.DateField(blank=True, null=True)),
                ('perro_vacunacion_sextuple_1_dosis_notas', models.TextField(blank=True, null=True)),
                ('gato_castrado', models.BooleanField(default=False)),
                ('gato_castrado_fecha', models.DateField(blank=True, null=True)),
                ('gato_castracion_fecha_futura', models.DateField(blank=True, null=True)),
                ('gato_castrado_notas', models.TextField(blank=True, null=True)),
                ('gato_desparasitado', models.BooleanField(default=False)),
                ('gato_desparasitado_fecha', models.DateField(blank=True, null=True)),
                ('gato_desparasitado_2', models.BooleanField(default=False)),
                ('gato_desparasitado_fecha_2', models.DateField(blank=True, null=True)),
                ('gato_desparasitado_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_desparasitado_notas', models.TextField(blank=True, null=True)),
                ('gato_pipeta_antipulgas', models.BooleanField(default=False)),
                ('gato_pipeta_antipulgas_fecha', models.DateField(blank=True, null=True)),
                ('gato_pipeta_antipulgas_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_pipeta_antipulgas_notas', models.TextField(blank=True, null=True)),
                ('gato_alimento', models.CharField(blank=True, max_length=255, null=True)),
                ('gato_cuidados_especiales', models.TextField(blank=True, null=True)),
                ('contrato_fecha', models.DateField(blank=True, null=True)),
                ('contrato_aceptado', models.BooleanField(default=False)),
                ('miembro_felis_catus_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(max_length=255)),
                ('email_enviado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('persona_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_dni', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('persona_ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_email', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_celular', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_facebook', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='catususer',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='catususer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.ContratoPersona'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.EstadoFormulario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.Animal'),
        ),
    ]
