# Generated by Django 2.0.13 on 2022-08-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0008_auto_20220807_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='miembro_felis_catus_nombre',
            new_name='miembro_adopcion_nombre',
        ),
    ]
