# Generated by Django 2.0.13 on 2022-08-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0009_auto_20220807_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoptante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catus.EstadoFormulario'),
        ),
    ]
