# Generated by Django 2.0.13 on 2022-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0010_auto_20220808_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='image_for_instagram',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
