# Generated by Django 2.0.13 on 2022-08-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0011_animalimage_image_for_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='image_centered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='image_font_size',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='image_posicion_edad_sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='image_posicion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
