# Generated by Django 2.0.13 on 2022-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0012_auto_20220810_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='image_layout',
            field=models.BooleanField(default=True),
        ),
    ]
