# Generated by Django 2.0.13 on 2022-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0013_animalimage_image_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_token_expire_at', models.CharField(blank=True, max_length=255, null=True)),
                ('business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
