# Generated by Django 2.0.13 on 2022-08-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0015_auto_20220811_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='facebook_token_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
