# Generated by Django 2.0.13 on 2022-08-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0016_auto_20220811_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='instagram_listo_para_publicar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='instagram_publicado',
            field=models.BooleanField(default=False),
        ),
    ]
