# Generated by Django 2.0.13 on 2022-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0018_animalimage_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='catususer',
            name='automatic_approve',
            field=models.BooleanField(default=False),
        ),
    ]
