# Generated by Django 2.0.13 on 2023-01-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0019_catususer_automatic_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='custom_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
