# Generated by Django 2.0.13 on 2023-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0022_animal_instagram_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='instagram_comment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
