# Generated by Django 2.0.13 on 2023-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0023_animal_instagram_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='chatgpt_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ig_url_for_chatgpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
