# Generated by Django 2.0.13 on 2023-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0024_auto_20230414_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGTPResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ig_url_for_chatgpt', models.CharField(blank=True, max_length=255, null=True)),
                ('chatgpt_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
