# Generated by Django 2.0.13 on 2023-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0025_chatgtpresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='mail_preguntar_adopcion_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('A', 'Macho y Hembra'), ('D', 'Desconocido')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='gato_sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('A', 'Macho y Hembra'), ('D', 'Desconocido')], default='D', max_length=1),
        ),
    ]
