# Generated by Django 2.0.13 on 2023-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0026_auto_20230712_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='catususer',
            name='no_preguntar_adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('D', 'En Adopción'), ('R', 'Reservado'), ('A', 'Adoptado'), ('E', 'Expirado')], default='D', max_length=2),
        ),
    ]
