# Generated by Django 2.0.13 on 2026-09-03 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0030_animal_revision_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgtpresponse',
            name='pedido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
