# Generated by Django 2.0.13 on 2026-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catus', '0031_chatgtpresponse_pedido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='instagram_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='instagram_intentos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='instagram_programado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='instagram_ultimo_intento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
